version: "3"
services:

    mysql:
      image: mariadb:10.3
      volumes:
        - mysqldata:/var/lib/mysql
      environment:
        MYSQL_DATABASE: video-parser
        MYSQL_USER: video-parser
        MYSQL_PASSWORD: video-parser
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

    webserver:
      restart: always
      image: nginx:alpine
      working_dir: /application
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - .:/application
      ports:
        - "1234:80"
      depends_on:
        - php-fpm
      links:
        - php-fpm

    php-fpm:
      build: .
      restart: always
      working_dir: /application
      volumes:
        - .:/application
        - ./runtime:/application/runtime
        - ./web/assets:/application/web/assets
        - ./runtime/logs/slowlog-site.log:/var/log/php-fpm/slowlog-site.log

volumes:
  mysqldata:
    driver: local
